\set ON_ERROR_STOP 1
CREATE DATABASE :dbname;
\c :dbname;

CREATE DOMAIN frequency_map AS BYTEA CHECK (length(VALUE) = 26);

CREATE TABLE job (
	job_id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	parent_job_id	BIGINT,
	frequency_map	frequency_map NOT NULL,
	start		INTEGER,
	finished	BOOLEAN NOT NULL
);
CREATE TABLE found_sentences (
	frequency_map_indices	BYTEA NOT NULL
);
