
CREATE DATABASE :dbname;
\c :dbname;

CREATE DOMAIN frequency_map AS BYTEA CHECK (length(VALUE) = 26);

CREATE TABLE job (
	job_id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	parent_job_id	BIGINT REFERENCES job(job_id),
	frequency_map	frequency_map NOT NULL,
	start		INTEGER
);
CREATE TABLE found_sentences (
	frequency_map_indices	BYTEA NOT NULL
);
